# -*- coding: utf-8 -*-
"""Exercise_Aula03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Iws84K7DV-lT84WGUTmCesEhg6XUZsMG
"""

names = ["Elias", "0235", "Fatoração", "Sal"]
print(len(names)) #possui 4 itens na lista.
print(names[0:2]) # fatia os itens da lista de até.

nuns = [9, 3, 5, 8]
names[2] = 7 #Substitui um item da lista.
print(len(nuns)) #possui 4 itens na lista.
print(nuns[0:3]) # fatia os itens da lista de até.

lista = names + nuns + ["Sol", "Lua", "Mar"]
print(len(lista))
print(lista)

lista1 = [19, "Python", True, 8.6, 100]
lista1.insert(3, False) #Acrescenta um itens na lista.
lista1.remove(8.6) #remove um itens selecionado.
lista1.reverse() #inverte a ordem da lista.
lista1.count(100) #também pode ser colocada no print 'print(lista1.count(100)).
lista1.pop() #remove o último item da lista.
del lista1[1] #remove por indice, e pode fazer o faitamento: del lista1[0:5]
print(lista1)

brasil = ["Nordeste",
          ["Pernanbuco",
           ["Recife", "Goiana"], 
           "Rio Grande do Norte",
           ["Natal"], 
           "Alagoas",
           ["Maceio"]], 
          "Norte", 
          ["Amazonas", "Acre", "Pará"]]
brasil[1][5][0]

var = "Polarização"
print(len(var)) #possui 10 letras na var.
print(var[0:5]) #faita as letras da lista de até.