# -*- coding: utf-8 -*-
"""Exercise_Aula04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jcuwFFtJNEOU_eXw3Dy-pB9aROjcE9Z3
"""

l = ["a", "b", "c",["d", "e", "f", ["g", "h", "i"]],"j", "k", "l",]
l[3][1]
l

#contando um contador.

import time #fazendo importações para dentro do python.
#exemplo do while

var = 0
while var <=5:
    print("ainda não, total=", var)
    time.sleep(3) #faz parte da biblioteca da importação
    var = var + 1

#contando nomes dentrode uma lista.

from time import sleep #trazendo um importação especifica do time.
#exemplo do for

itens = ["Anabell", "Beatriz", "Hanna", "Márcia", "Karol"]
for item in itens:
    print(item)
    sleep(2) #traz a funão especifica da importação antes selecionada.

#adicionando itens a uma lista.
sala = []
while len(sala) <= 1:
    nome = str(input("Informe o nome do aluno: "))
    sala.append(nome) # .append acrescenta elementos, neste caso para a nossa lista.
print(sala)

#Listando nome a nome com o for.
sala = []
while len(sala) <= 2:
    nome = str(input("Informe o nome do aluno: "))
    sala.append(nome)
for name in sala:
    print(name)

import random
l = ["a", "b", "c", "d", "e", "f"]
print(l[random.randint(0,5)])

import random
lista = ["a", "b", "c", "d", "e", "f"]
numeroAleatorio = random.randint(0,5)
print(numeroAleatorio) #imprime um numero aleatorio.
indice = lista [numeroAleatorio]
print(indice) #imprime o item da lista de acordo como numero.

#Adicionar nomes até quando quiser.

grupo = []
while True:
    acao = str(input("Digite 'ADD' para adicionar ou 'SAIR' para sair: ")).upper()
    if acao == "ADD":
        nome = str(input("Informe o nome: "))
        grupo.append(nome)
    elif acao == "SAIR":
        qtd = 1
        for nome in grupo:
            print(f"{qtd} {nome}") # adiciona o numero (sequencial) e o nome digitado anteriomente. 
            qtd = qtd + 1 # adiciona +1 (numerico) para cada nome que há na lista ( qtd = qud + 1 chama-se incremento e qtd = qtd - 1  chama-se decremento. mutito usado assim: qtd += 1 ou qtd -= 1)
        break #interrompe o sistema.
    else:
        print("Informação inválida")

import random

sortidos = ["Biscoito, Suco", "Amido"]
sortidosA = random.randint(0,2)
tentou = 1
while tentou <= 3:
    tentar = int(input("Digite um numero de 0 a 2 para passar: "))
    if tentar == sortidos:
        print(f"acertou! sua chave é{sortidosA} ")
        break
    elif tentar != sortidos:
        tentou += 1
        print("Tente mais uma vez")
    else:
        print("Limite esgotado!")