# -*- coding: utf-8 -*-
"""Exercise_Class05.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NibiSl9q0eI2bxXtJRxIgUQCANJpbNxd
"""

#Cadastro de alunos

alunos = []

print("Opção 1: Cadastrar Aluno \n Opção 2: Atualizar Aluno \n Opçaão 3: Excluir Aluno \n Opção 4: Pesquisar Aluno \n Opão 5: Ver Lista de Alunos \n Opão 6: Sair")

while True:
    resposta = int(input("O que deseja fazer? "))
    if resposta == 1:
        aluno = str(input("Informe o nome do aluno: \n")).capitalize()
        alunos.append(aluno)
        print(f"O aluno: {aluno} foi inserido!")
        continuar = input("Digite 'Enter' para continuar:")
    elif resposta == 2:
        busca = str(input("Informe o nome do Aluno: \n")).capitalize()
        if busca in alunos:
            att = str(input(f"Atualize o aluno {aluno} ")).capitalize()
            i = alunos.index(busca)
            alunos.pop(i) #remove
            alunos.append(att) #acrescenta o att
            print(f"O Aluno {att} foi Atualizado!")
            continuar = input("Digite 'Enter' para continuar:")
        else:
            print(f"O Aluno {busca} não está registrado.")
            continuar = input("Digite 'Enter' para continuar:")
    elif resposta == 3:
        busca = str(input("Informe o nome do Aluno: ")).capitalize()
        if busca in alunos:
            i = alunos.index(busca)
            alunos.pop(i)
            fb = input("Aluno excluido com sucesso. Enter para continuar...")
        else:
            fb = input("Alunos não encontrado. Enter para continuar...")
    elif resposta == 4:
        busca == str(input("Digite o nome que está procurando: ")).capitalize()
        if busca in alunos:
            print(f"O Aluno {busca} está resgistrado com indice {alunos.index(busca)}")
            fb = input("Enter para continuar...")
        else:
            print(f"O Aluno {busca} não está registrado.")
            fb = input("Enter para continuar...")
    elif resposta == 5:
        print("Todos os alunos cadastrados são: ")
        for aluno in alunos:
            print(aluno)
        fb = input("Enter para continuar...")
    elif resposta == 6:
        break
    else:
        print("Opçao inválida.")

#Tuplas
letra = "cachorro", "gato",[""]
letra[2][0] = "coelho"
print(letra)

letra = list(letra) #trasfoma uma tupla em uma lista em uma nova variavel.
letra = tuple(letra) #transforma uma lsita em uma tupla em uma nova variavel.

animais = "Cachorro", "Gato", "Coelho"
letras = list(animais)

animal2, *aninmal = letras
print(f"animal2 ")
print(f"ani")

carros = "Golf", "Corolla", "Civic", "Opalla","Tucson", "Elantra"
carro1,  carro2, carro3, carro4, carro5, carro6,= carros #Desempacotar
carro4

#Exercicio
#Popular uma lista com 'while True'
#Converter a lista em tupla 
#final e desempacotar.
cores = []

while True:
    name = input("Digite 'c' para Cores , para sair tecle Enter.").capitalize()
    if name == "C":
        cor = str(input("Digite sua cor favorita: ")).capitalize()
        cores.append(cor)
    else:
        print("Os seguintes itens foram adicionados:")
        cores = tuple(cores)
        for i in cores:
            print(i)
        print("\nAté Logo! \n     Encerrando...")
        break